### ISSUE TITLE
How long does it take to boot?

### ISSUE THREAD

**Issue by seanspotatobusiness** [craigmayhew/USBCleanser#1]
If this was switched off until needed, how long would you have to wait for it to boot? I figure the OS could be really cut-down compared to a normal Pi OS if it's sole purpose is to wipe USB drives and therefore never needs any kind of desktop environment or whatever so it should be able to boot really fast? Could it work on a Pi zero?

**Comment by craigmayhew** [comment]
Thanks for your interest! The code has been a little unloved for 3 years and so I suspect it won't work first time on the latest OS. When working, the boot time should be quick, only taking a minute or so. With little to no adjustment, I see no reason why this wouldn't work on the Pi zero!

What did you have in mind? Happy to help where I can.

**Comment by seanspotatobusiness** [comment]
Hi Craig, I read that a Pi Zero used in another project could boot in five seconds but obviously it must have been using a really basic operating system. If your system took a minute to boot, then I'm guessing it was a normal version of Raspbian with a GUI? I figure if it only boots to a command line then it should be far quicker than a minute (who has a minute?!) but I have no idea how to do this yet. I came across this post on Reddit: https://www.reddit.com/r/raspberry_pi/comments/4w5p53/idea_raspberry_pi_appliance_autoformat_usb_thumb/d68in83?utm_source=share&utm_medium=web2x

It reformats the drive instead of just deleting the content - I don't know what's better. I do know I'd like indicator lights to tell me when wiping is in progress and complete and also a button to actually initiate the wipe.

**Comment by seanspotatobusiness** [comment]
In order to minimise boot time, I'm now looking at possibly using Picore or maybe even Ultibo but even Picore will probably be a huge challenge to me and Ultibo sounds even more difficult to use (but would have a boot time of like two seconds).

**Comment by craigmayhew** [comment]
On the Pi I was using, it likely had a GUI, although after the initial setup we would have disconnected the screen and forgotten about this!

Depending on what security/speed trade off you were happy with, a fast format should be the fastest, though least secure.
